version: "3.8"

services:
  db:
    build:
      context: ./db

    ports: 
      - "7432:5432"

    environment: 
      POSTGRES_PASSWORD: secretpassword

    volumes: 
      - db-data:/var/lib/postgresql/data

volumes: 
  db-data: