# Generated by Django 3.0.8 on 2020-07-16 13:04

from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension()
    ]
