name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: app

        ports:
          - 5432/tcp
          
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install pip-tools
      run: |
        pip install --upgrade pip
        pip install pip-tools

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('project/requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('project/requirements/*.txt') }}

    - name: Install Dependencies
      working_directory: ./project
      run: |
        pip-sync project/requirements/base.txt project/requirements/dev.txt

    - name: Prepare test results
      working_directory: ./project
      run: |
        mkdir -p out/tests
        
    - name: Run Linter
      working_directory: ./project
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file out/tests/flake8-${{ matrix.python-version }}-project.txt

    - name: Run Tests
      working_directory: ./project
      run: |
        pytest --junitxml=out/tests/pytest-${{ matrix.python-version }}-project.xml
      env:
          SQL_PORT: ${{ job.services.postgres.ports[5432] }}
        
    - name: Archive Linter results
      uses: actions/upload-artifact@v2.0.1
      working_directory: ./project
      with:
        name: flake8-${{ matrix.python-version }}-results
        # A file, directory or wildcard pattern that describes what to upload
        path: out/tests/flake8-*.txt

    - name: Archive Test results
      uses: actions/upload-artifact@v2.0.1
      working_directory: ./project
      with:
        name: pytest-${{ matrix.python-version }}-results
        # A file, directory or wildcard pattern that describes what to upload
        path: out/tests/pytest-*.xml
