name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install Dependencies
      run: |
        pipenv install --dev --deploy

    - name: Run Linter
        run: |
          pipenv run flake8 --config=project/tox.ini

    - name: Run Tests
      run: |
        pipenv run pytest project
